### ISSUE TITLE
Rails 4 support?

### ISSUE THREAD

**Issue by keilmillerjr** [sinisterchipmunk/bot-away#4]
Hello! I absolutely love this gem. I'm just wondering if it is compatible with rails 4?

**Comment by keilmillerjr** [comment]
This is the error I get after running bundle:

```
keils-imac:keilmiller keiljr$ rails s
/Users/keiljr/.rvm/gems/ruby-2.0.0-p247@keilmiller/gems/activesupport-4.0.0/lib/active_support/core_ext/module/aliasing.rb:32:in `alias_method': undefined method `tag' for class `ActionView::Helpers::InstanceTag' (NameError)
    from /Users/keiljr/.rvm/gems/ruby-2.0.0-p247@keilmiller/gems/activesupport-4.0.0/lib/active_support/core_ext/module/aliasing.rb:32:in `alias_method_chain'
    from /Users/keiljr/.rvm/gems/ruby-2.0.0-p247@keilmiller/gems/bot-away-2.0.1/lib/bot-away/action_view/helpers/instance_tag.rb:96:in `<class:InstanceTag>'
    from /Users/keiljr/.rvm/gems/ruby-2.0.0-p247@keilmiller/gems/bot-away-2.0.1/lib/bot-away/action_view/helpers/instance_tag.rb:1:in `<top (required)>'
    from /Users/keiljr/.rvm/gems/ruby-2.0.0-p247@keilmiller/gems/bot-away-2.0.1/lib/bot-away.rb:6:in `require'
    from /Users/keiljr/.rvm/gems/ruby-2.0.0-p247@keilmiller/gems/bot-away-2.0.1/lib/bot-away.rb:6:in `<top (required)>'
    from /Users/keiljr/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `require'
    from /Users/keiljr/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `block (2 levels) in require'
    from /Users/keiljr/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `each'
    from /Users/keiljr/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `block in require'
    from /Users/keiljr/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `each'
    from /Users/keiljr/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `require'
    from /Users/keiljr/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler.rb:132:in `require'
    from /Users/keiljr/Projects/keilmiller/config/application.rb:7:in `<top (required)>'
    from /Users/keiljr/.rvm/gems/ruby-2.0.0-p247@keilmiller/gems/railties-4.0.0/lib/rails/commands.rb:76:in `require'
    from /Users/keiljr/.rvm/gems/ruby-2.0.0-p247@keilmiller/gems/railties-4.0.0/lib/rails/commands.rb:76:in `block in <top (required)>'
    from /Users/keiljr/.rvm/gems/ruby-2.0.0-p247@keilmiller/gems/railties-4.0.0/lib/rails/commands.rb:73:in `tap'
    from /Users/keiljr/.rvm/gems/ruby-2.0.0-p247@keilmiller/gems/railties-4.0.0/lib/rails/commands.rb:73:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'
```

Anyone have any ideas? This is an amazing gem and needs to be updated. Spam? Ain't nobody have time for that!

**Comment by keilmillerjr** [comment]
I hate to recommend another gem on some one else's repo. Especially when they worked hard to make it available for the rest of us. However, no response after 25 days means that development on this gem might be discontinued, and support for rails 4 is needed by many. So I would recommend anyone seeing this to try [gem 'invisible_captcha'](https://github.com/markets/invisible_captcha), which is compatible with Rails 4 and takes a similar approach to fighting spam.

**Comment by sinisterchipmunk** [comment]
The Rails 4 API is drastically different from 3.x and appears fundamentally incompatible with the current BotAway code base.

That's not to say I've lost interest in supporting this gem. It's been a lifesaver and I'm absolutely interested in supporting Rails 4.

Rails 4 is so different from Rails 3 in the areas that this gem needs to work in, that I'm probably going to bump the major version and redesign a lot of it. I'm starting to set the groundwork for that now. I don't know how long this will take -- time is a precious commodity of late -- and I'm willing to accept pull requests to make it happen.

**Comment by keilmillerjr** [comment]
Awesome! I wasn't aware that there was drastic api differences between the two rails versions. I have never looked into gem development. Rails docs a good place to start?

**Comment by sinisterchipmunk** [comment]
> Rails docs a good place to start?

Not in my opinion. The docs are great at describing how to use Rails, but not so much at describing how Rails works. You can get some value from the generated documentation as well as the comments left on sites like [api dock](http://apidock.com/rails) (though the latter doesn't seem to include Rails 4 yet), but in the end you can't get more authoritative than the [Rails source](http://github.com/rails/rails) code itself.

Never be afraid to jump into a project's source, even an intimidating one. It'll make you a better developer, and you'll learn tricks and techniques that you'd never have considered otherwise. If it's overwhelming at first, (it was for me), keep at it -- eventually it'll start to make sense, and you'll come away the better for it.

Having said that, if you're looking to write or contribute to a gem, there are a good number of tutorials out there on the topic; and if it's a Rails-specific gem that would add functionality to a Rails project, I highly recommend you start with [Railtie](http://api.rubyonrails.org/classes/Rails/Railtie.html), the core interface exposed by Rails that makes it so modular. Most projects designed for Rails define a subclass of `Railtie`, and they get a ton of logic "for free" by doing so.

**Comment by sinisterchipmunk** [comment]
Fyi, I've just pushed up the [first commit to the `rails4` branch](https://github.com/sinisterchipmunk/bot-away/tree/rails4) which essentially rewrites the gem for Rails 4 support. If you'd like to give it a try, feel free -- I look forward to getting some initial feedback on it. The tests pass but I've not tried it in an actual Rails 4 project yet, so treat it as an early alpha, or perhaps something less stable than that.

Also keep in mind that the API is still in flux as I try to decide how best to handle field whitelisting/blacklisting, locales, and a few other features that the Rails 3 version had but the new branch doesn't yet include.
